version: "3.8"

services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27888:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  gym-notes-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: "mongodb://mongoadmin:secret@mongo-db/?authSource=admin"
    ports:
      - "8080:3000"
    depends_on:
      - mongo-db
